const COLORS={green:'#16a34a',blue:'#2563eb',red:'#dc2626'};
const LABELS={green:'Сад / связанная школа',blue:'Школа с 1 класса',red:'Школа из списка'};
let PLACES=[];let CONTENT=null;const markers=new Map();const hiddenIds=new Set();
const map=L.map('map').setView([55.75,37.55],10);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
let layer=L.layerGroup().addTo(map);
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function visible(p,filter){if(filter==='all')return true;if(filter==='kindergarten')return p.kind==='green';if(filter==='first')return p.entity==='school'&&p.kind==='blue';return p.kind==='green'||(p.entity==='school'&&p.kind==='blue');}
function renderMap(){const filter=document.querySelector('#filter').value;layer.clearLayers();markers.clear();PLACES.filter(p=>!hiddenIds.has(p.id)&&visible(p,filter)).forEach(p=>{const m=L.circleMarker([p.lat,p.lon],{radius:p.entity==='kindergarten'?7:9,fillColor:COLORS[p.kind],color:'#fff',weight:2,fillOpacity:.9});m.bindPopup(`<div class="popup-title">${esc(p.name)}</div><div class="popup-kind">${LABELS[p.kind]} · ${p.entity==='kindergarten'?'детский сад':'школа'}</div><div>${esc(p.address)}</div><p>${p.website?`<a class="popup-link" href="${p.website}" target="_blank" rel="noopener">Сайт</a><br>`:''}<a class="popup-link" href="#place-${p.id}">Перейти к описанию ↓</a><br><a class="hide-link" href="#" onclick="hidePlace('${p.id}');return false;">скрыть</a></p>`);m.addTo(layer);markers.set(p.id,m);});}
function recordPlaceIds(record){return Array.isArray(record.place_ids)?record.place_ids:[];}
function recordIsHidden(record){const ids=recordPlaceIds(record);return ids.length>0&&ids.every(id=>hiddenIds.has(id));}
function hidePlace(id){const record=CONTENT.records.find(r=>recordPlaceIds(r).includes(id));if(record){recordPlaceIds(record).forEach(x=>hiddenIds.add(x));}else{hiddenIds.add(id);}renderMap();renderOverview();renderRecords();renderTrackNav();renderHidden();}
function restoreRecord(key){const record=CONTENT.records.find(r=>r.title===key);if(record){recordPlaceIds(record).forEach(id=>hiddenIds.delete(id));}else{hiddenIds.delete(key);}renderMap();renderOverview();renderRecords();renderTrackNav();renderHidden();}
function hideRecord(key){const record=CONTENT.records.find(r=>r.title===key);if(!record)return;recordPlaceIds(record).forEach(id=>hiddenIds.add(id));renderMap();renderOverview();renderRecords();renderTrackNav();renderHidden();}
function renderHidden(){const root=document.querySelector('#hidden-list');if(!root)return;const records=CONTENT.records.filter(r=>recordIsHidden(r));if(!records.length){root.innerHTML='<span class="review-note">Пока ничего не скрыто.</span>';return;}root.innerHTML='<ul class="hidden-list">'+records.map(r=>`<li>${esc(r.title)} <a class="restore-link" href="#" onclick="restoreRecord(${JSON.stringify(r.title)});return false;">вернуть</a></li>`).join('')+'</ul>';}
function openOnMap(id){const p=PLACES.find(x=>x.id===id);if(!p)return;document.querySelector('#filter').value='all';renderMap();map.setView([p.lat,p.lon],Math.max(map.getZoom(),13),{animate:true});const marker=markers.get(id);if(marker)marker.openPopup();document.querySelector('#map').scrollIntoView({behavior:'smooth',block:'start'});}
function linkHtml(s){return `<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)}</a>`;}
function uncertain(text){return /не найден|не подтвержд|уточн|не установлен|не раскрыт|не предусмотрен|не относится/i.test(text)?`<span class="uncertain">${esc(text)}</span>`:esc(text);}
function renderTrackNav(){const root=document.querySelector('#track-nav');if(!root)return;const tracks=new Map();CONTENT.records.filter(r=>!recordIsHidden(r)).forEach(r=>{const key=r.track||'Дошкольное образование';tracks.set(key,(tracks.get(key)||0)+1);});root.innerHTML=[...tracks].map(([track,count])=>`<a href="#track-${encodeURIComponent(track)}" onclick="openTrack(${JSON.stringify(track)});return false;">${esc(track)} (${count})</a>`).join('');}
function openTrack(track){const id=`track-${encodeURIComponent(track)}`;const el=document.getElementById(id);if(el){el.open=true;el.scrollIntoView({behavior:'smooth',block:'start'});}const nav=document.querySelector('.nav-dropdown');if(nav)nav.open=false;}
function renderOverview(){const root=document.querySelector('#overview');root.innerHTML=`<p class="overview-text">${esc(CONTENT.intro)}</p>`;CONTENT.overview.sections.forEach((s,i)=>{const block=document.createElement('section');block.className='overview-text';block.innerHTML=`<h3>${esc(s.title)}</h3><p>${esc(s.text)}</p>`;root.appendChild(block);if(s.title.startsWith('Сравнение'))root.appendChild(renderTable());});}
function renderTable(){const wrap=document.createElement('div');wrap.innerHTML=`<div class="toolbar"><label>Фильтры таблицы:</label><select id="class-filter"><option value="all">С какого класса: все</option></select><select id="grant-filter"><option value="all">Стипендии: все</option><option value="yes">есть/возможны</option><option value="no">не найдены/не заявлены</option></select></div><div class="stats" id="table-stats"></div><div class="table-wrap"><table class="comparison"><thead><tr><th>Школа</th><th>Тип</th><th>Траектория</th><th>С какого класса набор</th><th>Стоимость/год</th><th>Стипендии</th></tr></thead><tbody></tbody></table></div>`;const classSelect=wrap.querySelector('#class-filter'),grantSelect=wrap.querySelector('#grant-filter');const classes=[...new Set(CONTENT.table.map(r=>classBucket(r.admission)))].sort();classes.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=`С какого класса: ${c}`;classSelect.appendChild(o);});function fill(){const cf=classSelect.value,gf=grantSelect.value;const rows=CONTENT.table.filter(r=>{const record=CONTENT.records.find(x=>x.title===r.school);return !record||!recordIsHidden(record);}).filter(r=>(cf==='all'||classBucket(r.admission)===cf)&&(gf==='all'||(gf==='yes'?grantYes(r.scholarship):!grantYes(r.scholarship))));wrap.querySelector('tbody').innerHTML=rows.map(r=>`<tr><td><a href="#place-${esc(r.id)}">${esc(r.school)}</a></td><td>${esc(r.type)}</td><td>${esc(r.track||r.trajectory)}</td><td>${uncertain(r.admission)}</td><td>${uncertain(r.cost)}</td><td>${uncertain(r.scholarship)}</td></tr>`).join('');wrap.querySelector('#table-stats').textContent=`Показано строк: ${rows.length} из ${CONTENT.table.length}`;}classSelect.addEventListener('change',fill);grantSelect.addEventListener('change',fill);fill();return wrap;}
function classBucket(s){const m=String(s).match(/(?:с|в|во|для)\s+(?:примерно\s+)?(\d+)\s*(?:класс|лет)/i);return m?m[1]+' '+(m[0].toLowerCase().includes('лет')?'лет':'класс'):'уточнить';}
function grantYes(s){return /есть|возможн|фонд|грант|стипенд/i.test(s)&&!/не найден|не подтвержд|не раскрыт/i.test(s);}
function campusList(r){return `<div class="place-list">${r.place_text}</div>`;}
function recordHtml(r){const sites=r.websites.length?`<span class="site-links">Сайт: ${r.websites.map(linkHtml).join(' ')}</span>`:'<span class="review-note">Сайт/страница Википедии: не найдены в проверенных материалах.</span>';return `<article class="school-record" id="record-${esc(r.title)}"><p><strong>${esc(r.title)}</strong> — ${esc(r.body)} ${r.place_text} ${sites}. <a class="hide-link" href="#" onclick="hideRecord(${JSON.stringify(r.title)});return false;">скрыть</a></p></article>`;}
function renderRecords(){const root=document.querySelector('#schools');root.innerHTML='';const tracks=new Map();CONTENT.records.filter(r=>!recordIsHidden(r)).forEach(r=>{const k=r.track||'Дошкольное образование';if(!tracks.has(k))tracks.set(k,[]);tracks.get(k).push(r);});for(const [track,records] of tracks){const d=document.createElement('details');d.className='track-block';d.id=`track-${encodeURIComponent(track)}`;d.open=true;d.innerHTML=`<summary>${esc(track)} <span class="record-meta">(${records.length})</span></summary><div></div>`;const body=d.lastElementChild;body.innerHTML=records.map(recordHtml).join('');root.appendChild(d);}}
const ASSET_VERSION='hide-20260812-1';
async function boot(){try{[PLACES,CONTENT]=await Promise.all([fetch(`places.json?v=${ASSET_VERSION}`).then(r=>r.json()),fetch(`schools_content.json?v=${ASSET_VERSION}`).then(r=>r.json())]);renderMap();renderOverview();renderRecords();renderTrackNav();renderHidden();document.querySelector('#footer').textContent=CONTENT.footer;}catch(e){console.error(e);document.querySelector('#schools').textContent='Не удалось загрузить schools_content.json или places.json.';}}
document.querySelector('#filter').addEventListener('change',renderMap);boot();
