const COLORS={green:'#16a34a',blue:'#2563eb',red:'#dc2626'};
const LABELS={green:'Сад / связанная школа',blue:'Школа с 1 класса',red:'Школа из списка'};
let PLACES=[];
const map=L.map('map').setView([55.75,37.55],10);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
let layer=L.layerGroup().addTo(map);
const markers=new Map();
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function visible(p,filter){if(filter==='all')return true;if(filter==='kindergarten')return p.kind==='green';if(filter==='first')return p.entity==='school'&&p.kind==='blue';return p.kind==='green'||(p.entity==='school'&&p.kind==='blue');}
function renderMap(){const filter=document.querySelector('#filter').value;layer.clearLayers();markers.clear();PLACES.filter(p=>visible(p,filter)).forEach(p=>{const m=L.circleMarker([p.lat,p.lon],{radius:p.entity==='kindergarten'?7:9,fillColor:COLORS[p.kind],color:'#fff',weight:2,fillOpacity:.9});m.bindPopup(`<div class="popup-title">${esc(p.name)}</div><div class="popup-kind">${LABELS[p.kind]} · ${p.entity==='kindergarten'?'детский сад':'школа'}</div><div>${esc(p.address)}</div><p>${p.website?`<a class="popup-link" href="${p.website}" target="_blank" rel="noopener">Официальный сайт</a><br>`:''}<a class="popup-link" href="#${p.id}">Перейти к описанию ↓</a></p>`);m.addTo(layer);markers.set(p.id,m);});}
function openOnMap(id){const p=PLACES.find(x=>x.id===id);if(!p)return;document.querySelector('#filter').value='all';renderMap();map.setView([p.lat,p.lon],Math.max(map.getZoom(),13),{animate:true});const marker=markers.get(id);if(marker)marker.openPopup();document.querySelector('#map').scrollIntoView({behavior:'smooth',block:'start'});}
function card(p){return `<article class="card" id="${p.id}"><span class="tag ${p.kind}">${LABELS[p.kind]}</span><h3><a class="map-link" href="#map" onclick="openOnMap('${p.id}');return false;">${esc(p.name)}</a></h3><p><b>${p.entity==='kindergarten'?'Адрес сада':'Адрес школы'}:</b> ${esc(p.address)}</p>${p.associated_school?`<p><b>Связанная школа:</b> ${esc(p.associated_school)}</p>`:''}${p.notes?`<p class="section-note">${esc(p.notes)}</p>`:''}${p.source?`<p><a class="map-link" href="${p.source}" target="_blank" rel="noopener">Источник адреса</a></p>`:''}<p><a class="map-link" href="#map" onclick="openOnMap('${p.id}');return false;">↗ Показать на карте</a></p></article>`}
function renderCards(){const byGroup=new Map();for(const p of PLACES){if(!byGroup.has(p.group))byGroup.set(p.group,[]);byGroup.get(p.group).push(p);}const kindSchools=PLACES.filter(p=>p.entity==='school'&&p.kind==='green');const kindGardens=PLACES.filter(p=>p.entity==='kindergarten');const grouped=[];for(const [group,items] of byGroup){if(items.some(p=>p.entity==='school'&&p.kind==='green')||items.some(p=>p.entity==='kindergarten'))grouped.push(...items);}const first=PLACES.filter(p=>p.entity==='school'&&p.kind==='blue');const other=PLACES.filter(p=>p.entity==='school'&&p.kind==='red');const groups=[['kind-cards',grouped],['first-cards',first],['other-cards',other]];for(const [id,a] of groups){document.getElementById(id).innerHTML=a.map(card).join('')||'<p>Нет точек в этой категории.</p>';document.getElementById(id.replace('-cards','-count')).textContent=`${a.length} точек`;}}
async function loadSources(){for(const [id,file] of [['source-schools','Лучшие школы Москвы.md'],['source-kindergartens','Лучшие детские сады Москвы.md']]){try{const t=await fetch(encodeURI(file)).then(r=>r.text());document.getElementById(id).innerHTML=marked.parse(t)}catch(e){document.getElementById(id).textContent='Исходный файл недоступен.'}}}
fetch('places.json').then(r=>r.json()).then(data=>{PLACES=data;renderMap();renderCards();loadSources();});
document.querySelector('#filter').addEventListener('change',renderMap);
/* Data policy: verify every organization’s campuses from its official contacts page before changing places.json. */
