const COLORS={green:'#16a34a',blue:'#2563eb',red:'#dc2626'};
const LABELS={green:'Сад / связанная школа',blue:'Школа с 1 класса',red:'Школа из списка'};
let PLACES=[];
const map=L.map('map').setView([55.75,37.55],10);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);
let layer=L.layerGroup().addTo(map);
const markers=new Map();
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function visible(p,filter){if(filter==='all')return true;if(filter==='kindergarten')return p.kind==='green';if(filter==='first')return p.entity==='school'&&p.kind==='blue';return p.kind==='green'||(p.entity==='school'&&p.kind==='blue');}
function renderMap(){const filter=document.querySelector('#filter').value;layer.clearLayers();markers.clear();PLACES.filter(p=>visible(p,filter)).forEach(p=>{const m=L.circleMarker([p.lat,p.lon],{radius:p.entity==='kindergarten'?7:9,fillColor:COLORS[p.kind],color:'#fff',weight:2,fillOpacity:.9});m.bindPopup(`<div class="popup-title">${esc(p.name)}</div><div class="popup-kind">${LABELS[p.kind]} · ${p.entity==='kindergarten'?'детский сад':'школа'}</div><div>${esc(p.address)}</div><p>${p.website?`<a class="popup-link" href="${p.website}" target="_blank" rel="noopener">Официальный сайт</a><br>`:''}<a class="popup-link" href="#${p.id}">Перейти к описанию ↓</a></p>`);m.addTo(layer);markers.set(p.id,m);});}
function openOnMap(id){const p=PLACES.find(x=>x.id===id);if(!p)return;document.querySelector('#filter').value='all';renderMap();map.setView([p.lat,p.lon],Math.max(map.getZoom(),13),{animate:true});const marker=markers.get(id);if(marker)marker.openPopup();document.querySelector('#map').scrollIntoView({behavior:'smooth',block:'start'});}
function sourceEntry(p){const link=`<a class="map-link" href="#map" onclick="openOnMap('${p.id}');return false;">↗ Показать на карте</a>`;const address=`<p><b>${p.entity==='kindergarten'?'Адрес сада':'Адрес школы'}:</b> ${esc(p.address)}<br>${link}</p>`;const meta=p.associated_school?`<p><b>Связанная школа:</b> ${esc(p.associated_school)}</p>`:'';const note=p.notes?`<p class="section-note">${esc(p.notes)}</p>`:'';const source=p.source?`<p><a href="${p.source}" target="_blank" rel="noopener">Источник адреса</a></p>`:'';return `<div class="place-entry" id="${p.id}"><h4>${esc(p.name)}</h4>${address}${meta}${note}${source}</div>`;}
function appendMapDetails(containerId,items,title){const root=document.getElementById(containerId);const box=document.createElement('section');box.className='map-details';box.innerHTML=`<h3>${title}</h3>${items.map(sourceEntry).join('')}`;root.appendChild(box);}
async function loadSources(){const specs=[['source-schools','Лучшие школы Москвы.md','школа'],['source-kindergartens','Лучшие детские сады Москвы.md','детский сад']];for(const [id,file,type] of specs){try{const t=await fetch(encodeURI(file)).then(r=>r.text());const root=document.getElementById(id);root.innerHTML=marked.parse(t);appendMapDetails(id,PLACES.filter(p=>p.entity===type),`Данные карты: адреса и переходы к точкам (${type})`);}catch(e){document.getElementById(id).textContent='Исходный файл недоступен.'}}}
fetch('places.json').then(r=>r.json()).then(data=>{PLACES=data;renderMap();loadSources();});
document.querySelector('#filter').addEventListener('change',renderMap);
/* places.json is the editable data layer; verify every campus from official contacts before changing it. */
